FROM php:7.2-apache
RUN apt-get update
RUN apt-get install -y \
  git vim unzip \
  && docker-php-ext-install pdo_mysql mysqli mbstring
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
RUN chmod 775 /usr/local/bin/composer
